version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '123'
    volumes:
      - /home/tiago/eclipse-workspace/crudjsp/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080